site_name: The Number Line
theme:
  name: material
  favicon: assets/img/number-line-logo-favicon-teal.jpg
  logo: assets/img/number-line-logo-1.png
  site_url: https://fishfugu.github.io/the-number-line/
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  extra:
    analytics:
      provider: google
      property: G-DV0QCN1Y37
    consent:
      title: Cookie consent
      description: >- 
        We use cookies to recognise your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.
  features:
    - content.code.annotate
    - content.action.edit
    - content.tooltips
    - content.blog # Enable built-in Material blog
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.share
    - search.exclude

use_directory_urls: false

copyright: >
  Copyright &copy; 2016 - 2025 Nicholas Gledhill
  &nbsp &nbsp -- &nbsp &nbsp
  <a href="#__consent">Change cookie settings</a>

plugins:
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 20
      # TODO: create post exerpts and make this required
      post_excerpt: optional
      # all content before the separator is considered to be part of the excerpt:
      post_excerpt_separator: <!-- more -->
      post_readtime: true
      post_readtime_words_per_minute: 200
      archive: true
      archive_name: Archive
      archive_date_format: MMMM yyyy

site_url: https://fishfugu.github.io/the-number-line/

markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - meta # Enables metadata in Markdown files

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/contrib/auto-render.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css
  - assets/custom.css

nav:
  - Home: index.md
  - Elliptic Curves:
      - Elliptic Curves 101:
          - Introduction: elliptic-curves/elliptic-curves-101/010-ec-101-introduction.md
          - What is a Set, a Group, a Ring, and a Field?: elliptic-curves/elliptic-curves-101/020-set-group-ring-field.md
          - The Discrete Logarithm Problem: elliptic-curves/elliptic-curves-101/030-discrete-logarithm.md
          - Elliptic Curves over \( \mathbb{R} \): elliptic-curves/elliptic-curves-101/040-elliptic-curves-real.md
          - Theorem / Proof, A line connecting P and Q always intersects a third point: elliptic-curves/elliptic-curves-101/050-theorem-line-intersection.md
          - The Additive Inverse: elliptic-curves/elliptic-curves-101/060-additive-inverse.md
          - Adding Points, Doubling Points: elliptic-curves/elliptic-curves-101/070-point-addition.md
          - Expanding from Weierstrass To General Form: elliptic-curves/elliptic-curves-101/080-weierstrass-general.md
          - ~~ Associativity ~~: elliptic-curves/elliptic-curves-101/090-associativity.md
          - ~~ The Projective Plane ~~: elliptic-curves/elliptic-curves-101/100-projective-plane.md
          - ~~ Homogeneous Equations ~~: elliptic-curves/elliptic-curves-101/110-homogeneous-equations.md
          - ~~ Elliptic Curves In a Finite Field ~~: elliptic-curves/elliptic-curves-101/120-elliptic-curves-finite-field.md
          - ~~ The Modular Multiplicative Inverse ~~: elliptic-curves/elliptic-curves-101/130-modular-multiplicative-inverse.md
          - ~~ The Slope of an Elliptic Curve (Formal Derivative) ~~: elliptic-curves/elliptic-curves-101/140-slope-formal-derivative.md
          - ~~ Arithmetic In A Finite Field ~~: elliptic-curves/elliptic-curves-101/150-arithmetic-finite-field.md
          - ~~ Doubling Points in a Finite Field ~~: elliptic-curves/elliptic-curves-101/160-doubling-points-finite-field.md
          - ~~ Acknowledgements and Bibliography ~~: elliptic-curves/elliptic-curves-101/900-acknowledgements-bibliography.md
          - test page: elliptic-curves/elliptic-curves-101/test.md
      - Practical Cryptography:
          - Threshold Crytography: elliptic-curves/practical-cryptography/010-threshold-cryptography.md
          - The Mathematics of Threshold Cryptography: elliptic-curves/practical-cryptography/020-mathematics-of-threshold.md
      - References (Under Construction): elliptic-curves/bibliography-references.md
  - Blog:
      - blog/index.md
